### ISSUE TITLE
[err] The specified host is unknown

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/guide-microprofile-rest-client#135]
In the "Testing the application" section, After creating the RestClientIT.java when running the tests in dev mode it comes back with :
`[INFO] [WARNING ] Interceptor for {http://client.inventory.guides.openliberty.io/}SystemClient has thrown exception, 
 unwinding now`
`[INFO] Could not send Message.`
`[INFO] [err] The specified host is unknown.`

Screenshot bellow:

![image](https://user-images.githubusercontent.com/56261244/91493752-aa29ac00-e8af-11ea-954c-06eaed397769.png)

Seems to be similar issue to [this one](https://github.com/OpenLiberty/ci.maven/issues/520)

**Comment by AustinSeto** [comment]
Error "The specified host is unknown" is printed whenever a request is made to a bad or unknown host name. This causes the test `testUnknownHost` in `InventoryEndpointIT.java` to trigger the message. Perhaps an alternate way to handle this is desired?

**Comment by AustinSeto** [comment]
This is mentioned in https://github.com/openliberty/guides-common/issues/367

**Comment by gkwan-ibm** [comment]
close
- the issue was fixed
