### ISSUE TITLE
Improve the code

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-rest-client#57]
- io.openliberty.guides.inventory.InventoryManager
  - `private List<SystemData> systems = Collections.synchronizedList(new ArrayList<>());`
  - to  `private List<SystemData> systems = Collections.synchronizedList(new ArrayList<SystemData>());`
- io.openliberty.guides.inventory.model.SystemData
  - following lines are not necessary
```
      import java.util.ArrayList;
      import java.util.List;
```

**Comment by DannyS03** [comment]
Update complete. See https://openliberty.io/guides/microprofile-rest-client.html for improvements.
