### ISSUE TITLE
Update guide to use MP Rest Client 1.2 features

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/guide-microprofile-rest-client#70]
Currently, this guide uses the MP Rest Client 1.1 API.  This should be upgraded to use the MP Rest Client 1.2 APIs - part of MicroProfile 2.2.

Probably the easiest and most beneficial change would be to specify the baseURI for the client directly in the `@RegisterRestClient` annotation rather than specifying it via MP Config (or rather - mention that MP Config can override the value in the annotation).

Additional updates could include using `@ClientHeaderParam` to specify HTTP headers without altering the client interface method signatures.  We could also specify connect and read timeouts using the new APIs and/or MP Config settings.

This improvement should occur after MP Rest Client 1.2 ships - see epic issue [5941](
https://github.com/OpenLiberty/open-liberty/issues/5941) for more details.

**Comment by evelinec** [comment]
Fixed in https://github.com/OpenLiberty/guide-microprofile-rest-client/pull/99
