### ISSUE TITLE
use liberty:run-server instead of liberty:start-server

### ISSUE THREAD

**Issue by m86194** [OpenLiberty/guide-microprofile-rest-client#94]
I would suggest that all the tutorials are rewritten using liberty:run-server

To my understanding this brings OpenLiberty to the foreground, instead of running headless.  For developers trying to find out what happens using e.g. System.out.println (which is crude but simple enough that it cuts through all the magic going on) is essential.

As these are tutorials and not demonstrations, focus should be on how to debug things easily because there might be typos, something missed, misplaced fiiles etc which are subtle enough to be hard to see for an experienced developer, who are unfamiliar with the way OpenLiberty works.

Also I ran into an issue having two deployed apps named "rest" (or something like that) causing OpenLiberty to reject the deployment.  After some experiments it was found that "mvn clean" was needed before "mvn install".  This is very slow and something that experienced developers take notice of.  If there is a faster workcycle I would suggest explaining and using that.

**Comment by yeekangc** [comment]
Thank you for your feedback, @m86194.  Appreciate it.

We are working to switch the guides to use the new [dev mode](https://blog.sebastian-daschner.com/entries/openliberty-plugin-dev-mode) in our build plugin, which is intended to make it easier for for developers to code, test and debug.  It should help to provide immediate feedback to the developers so you can focus on the code and getting it to work.

Please stay tuned and we'd appreciate your feedback on dev mode too.

**Comment by DannyS03** [comment]
- Guide converted to dev mode.
- See:
  - https://github.com/OpenLiberty/guide-microprofile-rest-client/pull/109
  - https://openliberty.io/guides/microprofile-rest-client.html#getting-started

- Feedback is encouraged on dev mode implementation/experience.
