### ISSUE TITLE
Peer Review: New 1.2/1.3 features

### ISSUE THREAD

**Issue by DannyS03** [OpenLiberty/guide-microprofile-rest-client#98]
Peer Review: review to be done by a peer member. 

- [x] Check that the guide has working instruction and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Define test coverage and review with team (including guide contributor, if available)
- [x] Define detail test cases 
- [x] Consider corner cases targeting the specific guide
- [x] Consider different platform tests, ie, Mac, Windows, Linux
- [x] Consider corner cases UI tests
- [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
- [x] Consider testing the `curl` command for URL visits
- [x] Consider Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, VS.code, Eclipse, IntelliJ, Microclimate
- [x] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
- Table of contents 
- Headings
- Paragraphs
- code snippets
- outputs
- links
- hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by DannyS03** [comment]
## Enhancements 
**What you'll learn**
- [ ] Might be a good idea to have a link regarding `Context and Dependency Injection (CDI)` and `RestClientBuilder` for user reference. 

<img width="576" alt="image" src="https://user-images.githubusercontent.com/25497083/67685137-e6783d00-f96a-11e9-96cd-118c1d0a9815.png">

**Comment by DannyS03** [comment]
Overall changes and additions are good!

**Comment by evelinec** [comment]
Added a link to CDI doc as the online doc is very good. Also added a link to the intro blog post for `RestClientBuilder`. Hope these help. 

Also fixed the hotspot issue.
